# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.GretchenHeimlich.github.io
title: Gretchen Heimlich
email: gheim001@ucr.edu
author: Gretchen Heimlich
description: "Gretchen's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/GretchenHeimlich  
  - icon: envelope-o
    title: email
    url: mailto:danicassol@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/GretchenHeimlich/
  - icon: file-pdf-o
    title: CV
    url: img/CassolDanielaCV.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
  - icon: twitter
    title: twitter
    url: https://twitter.com/danicassol

